# --------------------------------------------------------------
# Common
# --------------------------------------------------------------
namespace: apps
storage_class: "opt-storage"
rancher_kubeconfig: "/etc/rancher/rke2/rke2.yaml"
# --------------------------------------------------------------


# --------------------------------------------------------------
# deployment strategies config
# --------------------------------------------------------------
canary_percentage: 10
ab_test_percentage: 20
canary_user_ips: []
shadow_replicas: 1
replicas: 2
app_host: "{{ hostvars[TARGET_NODE]['ansible_host'] }}"
# --------------------------------------------------------------



# --------------------------------------------------------------
# nextcloud config
# --------------------------------------------------------------
nextcloud_app_name: "nextcloud"
nextcloud_image: "nextcloud:latest"
nextcloud_secret_name: "nextcloud-secret"
nextcloud_service_name: "nextcloud-service"
nextcloud_pvc_name: "nextcloud-data-pvc"
nextcloud_ingress_name: "nextcloud-ingress"
nextcloud_config_name: "nextcloud-config"
nextcloud_trusted_domains: "cloud.waldhauser.sk localhost"
nextcloud_url: "https://cloud.waldhauser.sk"
nextcloud_protocol: "https"
nextcloud_host: "cloud.waldhauser.sk"

# admin credentials
nextcloud_admin_user: "admin"
nextcloud_admin_password: "your_secure_admin_password"

# resources
nextcloud_cpu_request: "256m"
nextcloud_memory_request: "512Mi"
nextcloud_cpu_limit: "512m"
nextcloud_memory_limit: "1Gi"

# PHP configuration
nextcloud_php_memory_limit: "512M"
nextcloud_php_upload_limit: "10G"

# storage
nextcloud_storage_size: "50Gi" # NEXTCLOUD FILE STORAGE SIZE
nextcloud_folder: "/opt/nextcloud-storage"

# Ingress configuration
nextcloud_ssl_redirect: "false"
nextcloud_proxy_body_size: "10G"

# PHP configuration
php_memory_limit: "512M"
php_upload_limit: "10G"

# Resource Limits
memory_request: "256Mi"
cpu_request: "100m"
memory_limit: "1Gi"
cpu_limit: "500m"

# Ingress configuration
ssl_redirect: "false"
proxy_body_size: "10G"
# --------------------------------------------------------------

# --------------------------------------------------------------
# Redis Configuration (for Nextcloud session management)
# --------------------------------------------------------------
redis_app_name: "redis"
redis_secret_name: "redis-secret"
redis_config_name: "redis-config"
redis_pvc_name: "redis-data-pvc"
redis_data_folder: "/opt/redis-data"
redis_storage_size: "2Gi"
redis_password: "redisPasswort12354"

# Redis Resource Limits
redis_memory_request: "128Mi"
redis_cpu_request: "100m"
redis_memory_limit: "256Mi"
redis_cpu_limit: "200m"
redis_max_memory: "200mb"
# --------------------------------------------------------------

# --------------------------------------------------------------
# postgre config
# --------------------------------------------------------------
postgresql_app_name: "postgresql"
postgresql_image: "postgres:15-alpine"
postgresql_secret_name: "postgresql-secret"
postgresql_service_name: "postgresql-service"
postgresql_pv_name: "postgresql-data-pv"
postgresql_pvc_name: "postgresql-data-pvc"
postgresql_configmap_name: "postgresql-config"
postgresql_ingress_policy_name: "postgresql-ingress-policy"

# Storage Configuration
postgresql_storage_size: "15Gi" # NEXTCLOUD USER AUTH, PERMS, CONTACTS, INDEXES... STORAGE SIZE
postgresql_data_folder: "/data/postgresql"
pv_reclaim_policy: "Retain"

# Resource Limits
postgre_mem_request: "256Mi"
postgre_cpu_request: "100m"
postgre_mem_limit: "1Gi"
postgre_cpu_limit: "500m"

postgresql_connection:
  host: "postgresql-service"
  port: 5432
  database: "nextcloud"
  username: "nextcloud_user"      
  password: "nextcloud_password"  
  postgres_user: "postgres"       # Admin user for postgre
  postgres_password: "adminpassword"  # Admin password for postgre
# --------------------------------------------------------------