# ------------------------------------------------------------
# DEPLOYMENT STRATEGIES
# ------------------------------------------------------------

# ------------------------------------------------------------
# BLUE GREEN DEPLOYMENT STRATEGY
# ------------------------------------------------------------
nextcloud_bluegreen_deployment:
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: "{{ nextcloud_app_name }}-{{ target_nextcloud_env }}"
    namespace: "{{ namespace }}"
    labels:
      app: "{{ nextcloud_app_name }}"
      env: "{{ target_nextcloud_env }}"
  spec:
    replicas: "{{ replicas }}"
    selector:
      matchLabels:
        app: "{{ nextcloud_app_name }}"
        env: "{{ target_nextcloud_env }}"
    template:
      metadata:
        labels:
          app: "{{ nextcloud_app_name }}"
          env: "{{ target_nextcloud_env }}"
      spec:
        containers:
        - name: nextcloud-app
          image: "{{ nextcloud_image }}"
          ports:
          - containerPort: 80
            name: http
          env:
          # Nextcloud Admin Configuration
          - name: NEXTCLOUD_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: "{{ nextcloud_secret_name | default('nextcloud-secret') }}"
                key: NEXTCLOUD_ADMIN_USER
          - name: NEXTCLOUD_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ nextcloud_secret_name | default('nextcloud-secret') }}"
                key: NEXTCLOUD_ADMIN_PASSWORD
          
          # PostgreSQL Database Configuration
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: "{{ postgresql_secret_name | default('postgresql-secret') }}"
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: "{{ postgresql_secret_name | default('postgresql-secret') }}"
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ postgresql_secret_name | default('postgresql-secret') }}"
                key: POSTGRES_PASSWORD
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: "{{ postgresql_secret_name | default('postgresql-secret') }}"
                key: POSTGRES_HOST
          - name: POSTGRES_PORT
            value: "5432"
          
          # Nextcloud specific settings
          - name: NEXTCLOUD_TRUSTED_DOMAINS
            value: "{{ nextcloud_trusted_domains | default('localhost') }}"
          - name: OVERWRITEPROTOCOL
            value: "{{ nextcloud_protocol | default('https') }}"
          - name: OVERWRITEHOST
            value: "{{ nextcloud_host | default('localhost') }}"
          - name: OVERWRITECLIURL
            value: "{{ nextcloud_protocol | default('https') }}://{{ nextcloud_host | default('localhost') }}"
          
          # PHP Configuration for better performance
          - name: PHP_MEMORY_LIMIT
            value: "{{ nextcloud_php_memory_limit | default('512M') }}"
          - name: PHP_UPLOAD_LIMIT
            value: "{{ nextcloud_php_upload_limit | default('10G') }}"
          
          # Redis Configuration
          - name: REDIS_HOST
            value: "redis-service"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ redis_secret_name | default('redis-secret') }}"
                key: REDIS_PASSWORD
          
          volumeMounts:
          - name: nextcloud-data
            mountPath: /var/www/html
          # - name: nextcloud-config
          #   mountPath: /var/www/html/config/redis.config.php
          #   subPath: redis.config.php
          # - name: php-redis-session
          #   mountPath: /usr/local/etc/php/conf.d/redis-session.ini
          #   subPath: redis-session.ini

            
          readinessProbe:
            httpGet:
              path: /status.php
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 30
            failureThreshold: 6
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /status.php
              port: 80
            initialDelaySeconds: 240
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 3
            
          resources:
            requests:
              memory: "{{ nextcloud_memory_request | default('256Mi') }}"
              cpu: "{{ nextcloud_cpu_request | default('100m') }}"
            limits:
              memory: "{{ nextcloud_memory_limit | default('1Gi') }}"
              cpu: "{{ nextcloud_cpu_limit | default('500m') }}"
              
        volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: "{{ nextcloud_pvc_name | default('nextcloud-data-pvc') }}"
        # - name: nextcloud-config
        #   configMap:
        #     name: "{{ nextcloud_config_name | default('nextcloud-config') }}"
        # - name: php-redis-session
        #   configMap:
        #     name: nextcloud-php-redis-session


# ------------------------------------------------------------
# ROLLING DEPLOYMENT STRATEGY
# ------------------------------------------------------------

nextcloud_rolling_deployment:
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: "{{ nextcloud_app_name }}"
    namespace: "{{ namespace }}"
    labels:
      app: "{{ nextcloud_app_name }}"
  spec:
    replicas: "{{ replicas }}"
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
    selector:
      matchLabels:
        app: "{{ nextcloud_app_name }}"
    template:
      metadata:
        labels:
          app: "{{ nextcloud_app_name }}"
      spec:
        containers:
        - name: nextcloud-app
          image: "{{ nextcloud_image }}"
          ports:
          - containerPort: 80
            name: http
          env:
          # Nextcloud Admin Configuration
          - name: NEXTCLOUD_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: "{{ nextcloud_secret_name | default('nextcloud-secret') }}"
                key: NEXTCLOUD_ADMIN_USER
          - name: NEXTCLOUD_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ nextcloud_secret_name | default('nextcloud-secret') }}"
                key: NEXTCLOUD_ADMIN_PASSWORD

          # PostgreSQL Database Configuration
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: "{{ postgresql_secret_name | default('postgresql-secret') }}"
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: "{{ postgresql_secret_name | default('postgresql-secret') }}"
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ postgresql_secret_name | default('postgresql-secret') }}"
                key: POSTGRES_PASSWORD
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: "{{ postgresql_secret_name | default('postgresql-secret') }}"
                key: POSTGRES_HOST
          - name: POSTGRES_PORT
            value: "5432"

          # Nextcloud specific settings
          - name: NEXTCLOUD_TRUSTED_DOMAINS
            value: "{{ nextcloud_trusted_domains | default('localhost') }}"
          - name: OVERWRITEPROTOCOL
            value: "{{ nextcloud_protocol | default('https') }}"
          - name: OVERWRITEHOST
            value: "{{ nextcloud_host | default('localhost') }}"
          - name: OVERWRITECLIURL
            value: "{{ nextcloud_protocol | default('https') }}://{{ nextcloud_host | default('localhost') }}"

          # PHP Configuration for better performance
          - name: PHP_MEMORY_LIMIT
            value: "{{ nextcloud_php_memory_limit | default('512M') }}"
          - name: PHP_UPLOAD_LIMIT
            value: "{{ nextcloud_php_upload_limit | default('10G') }}"

          # Redis Configuration
          - name: REDIS_HOST
            value: "redis-service"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ redis_secret_name | default('redis-secret') }}"
                key: REDIS_PASSWORD


          volumeMounts:
          - name: nextcloud-data
            mountPath: /var/www/html
          # - name: nextcloud-config
          #   mountPath: /var/www/html/config/redis.config.php
          #   subPath: redis.config.php
          # - name: php-redis-session
          #   mountPath: /usr/local/etc/php/conf.d/redis-session.ini
          #   subPath: redis-session.ini

          readinessProbe:
            httpGet:
              path: /status.php
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 30
            failureThreshold: 6
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /status.php
              port: 80
            initialDelaySeconds: 240
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 3

          resources:
            requests:
              memory: "{{ nextcloud_memory_request | default('256Mi') }}"
              cpu: "{{ nextcloud_cpu_request | default('100m') }}"
            limits:
              memory: "{{ nextcloud_memory_limit | default('1Gi') }}"
              cpu: "{{ nextcloud_cpu_limit | default('500m') }}"

        volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: "{{ nextcloud_pvc_name | default('nextcloud-data-pvc') }}"
        # - name: nextcloud-config
        #   configMap:
        #     name: "{{ nextcloud_config_name | default('nextcloud-config') }}"
        # - name: php-redis-session
        #   configMap:
        #     name: nextcloud-php-redis-session

# ------------------------------------------------------------
# RECREATE DEPLOYMENT STRATEGY
# ------------------------------------------------------------

nextcloud_recreate_deployment:
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: "{{ nextcloud_app_name }}"
    namespace: "{{ namespace }}"
    labels:
      app: "{{ nextcloud_app_name }}"
  spec:
    replicas: "{{ replicas }}"
    strategy:
      type: Recreate
    selector:
      matchLabels:
        app: "{{ nextcloud_app_name }}"
    template:
      metadata:
        labels:
          app: "{{ nextcloud_app_name }}"
      spec:
        containers:
        - name: nextcloud-app
          image: "{{ nextcloud_image }}"
          ports:
          - containerPort: 80
            name: http
          env:
          # Nextcloud Admin Configuration
          - name: NEXTCLOUD_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: "{{ nextcloud_secret_name | default('nextcloud-secret') }}"
                key: NEXTCLOUD_ADMIN_USER
          - name: NEXTCLOUD_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ nextcloud_secret_name | default('nextcloud-secret') }}"
                key: NEXTCLOUD_ADMIN_PASSWORD

          # PostgreSQL Database Configuration
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: "{{ postgresql_secret_name | default('postgresql-secret') }}"
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: "{{ postgresql_secret_name | default('postgresql-secret') }}"
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ postgresql_secret_name | default('postgresql-secret') }}"
                key: POSTGRES_PASSWORD
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: "{{ postgresql_secret_name | default('postgresql-secret') }}"
                key: POSTGRES_HOST
          - name: POSTGRES_PORT
            value: "5432"

          # Nextcloud specific settings
          - name: NEXTCLOUD_TRUSTED_DOMAINS
            value: "{{ nextcloud_trusted_domains | default('localhost') }}"
          - name: OVERWRITEPROTOCOL
            value: "{{ nextcloud_protocol | default('https') }}"
          - name: OVERWRITEHOST
            value: "{{ nextcloud_host | default('localhost') }}"
          - name: OVERWRITECLIURL
            value: "{{ nextcloud_protocol | default('https') }}://{{ nextcloud_host | default('localhost') }}"

          # PHP Configuration for better performance
          - name: PHP_MEMORY_LIMIT
            value: "{{ nextcloud_php_memory_limit | default('512M') }}"
          - name: PHP_UPLOAD_LIMIT
            value: "{{ nextcloud_php_upload_limit | default('10G') }}"

          # Redis Configuration
          - name: REDIS_HOST
            value: "redis-service"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ redis_secret_name | default('redis-secret') }}"
                key: REDIS_PASSWORD

          volumeMounts:
          - name: nextcloud-data
            mountPath: /var/www/html
          # - name: nextcloud-config
          #   mountPath: /var/www/html/config/redis.config.php
          #   subPath: redis.config.php
          # - name: php-redis-session
          #   mountPath: /usr/local/etc/php/conf.d/redis-session.ini
          #   subPath: redis-session.ini

          # readinessProbe:
          #   httpGet:
          #     path: /status.php
          #     port: 80
          #   initialDelaySeconds: 120
          #   periodSeconds: 10
          #   timeoutSeconds: 30
          #   failureThreshold: 6
          #   successThreshold: 1
          # livenessProbe:
          #   httpGet:
          #     path: /status.php
          #     port: 80
          #   initialDelaySeconds: 240
          #   periodSeconds: 30
          #   timeoutSeconds: 30
          #   failureThreshold: 3

          resources:
            requests:
              memory: "{{ nextcloud_memory_request | default('256Mi') }}"
              cpu: "{{ nextcloud_cpu_request | default('100m') }}"
            limits:
              memory: "{{ nextcloud_memory_limit | default('1Gi') }}"
              cpu: "{{ nextcloud_cpu_limit | default('500m') }}"

        volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: "{{ nextcloud_pvc_name | default('nextcloud-data-pvc') }}"
        # - name: nextcloud-config
        #   configMap:
        #     name: "{{ nextcloud_config_name | default('nextcloud-config') }}"
        # - name: php-redis-session
        #   configMap:
        #     name: nextcloud-php-redis-session

# ------------------------------------------------------------
# PERSISTENT VOLUME
# ------------------------------------------------------------

nextcloud_data_pv:
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: "nextcloud-data-pv"
    labels:
      app: "{{ nextcloud_app_name }}"
  spec:
    capacity:
      storage: "{{ nextcloud_storage_size | default('50Gi') }}"
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: "{{ storage_class | default('opt-storage') }}"
    hostPath:
      path: "{{ nextcloud_folder | default('/opt/nextcloud-storage') }}"
      type: DirectoryOrCreate

# ------------------------------------------------------------
# PERSISTENT VOLUME CLAIM
# ------------------------------------------------------------

nextcloud_data_pvc:
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: "{{ nextcloud_pvc_name | default('nextcloud-data-pvc') }}"
    namespace: "{{ namespace }}"
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: "{{ nextcloud_storage_size | default('10Gi') }}"
    storageClassName: "{{ storage_class }}"

# ------------------------------------------------------------
# SECRET
# ------------------------------------------------------------

nextcloud_secret:
  apiVersion: v1
  kind: Secret
  metadata:
    name: "{{ nextcloud_secret_name | default('nextcloud-secret') }}"
    namespace: "{{ namespace }}"
  type: Opaque
  data:
    NEXTCLOUD_ADMIN_USER: "{{ nextcloud_admin_user | b64encode }}"
    NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_admin_password | b64encode }}"

# ------------------------------------------------------------
# CLUSTERIP SERVICE
# ------------------------------------------------------------

nextcloud_service:
  apiVersion: v1
  kind: Service
  metadata:
    name: "{{ nextcloud_service_name | default(nextcloud_app_name + '-service') }}"
    namespace: "{{ namespace }}"
    labels:
      app: "{{ nextcloud_app_name }}"
  spec:
    selector:
      app: "{{ nextcloud_app_name }}"
    ports:
      - port: 80
        targetPort: 80
        name: http
    type: ClusterIP

# ------------------------------------------------------------
# INGRESS
# ------------------------------------------------------------

nextcloud_ingress:
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: "{{ nextcloud_ingress_name | default('nextcloud-ingress') }}"
    namespace: "{{ namespace }}"
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "{{ nextcloud_ssl_redirect | default('false') }}"
      nginx.ingress.kubernetes.io/proxy-body-size: "{{ nextcloud_proxy_body_size | default('10G') }}"
      nginx.ingress.kubernetes.io/proxy-buffering: "off"
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
  spec:
    rules:
    - host: "{{ nextcloud_host | default('localhost') }}"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: "{{ nextcloud_service_name | default(nextcloud_app_name + '-service') }}"
              port: 
                number: 80

