---
- name: Check prerequisites
  hosts: localhost
  become: true
  roles:
    - role: 01_local_prerequisites
      tags: always

- name: Check server prerequisites
  hosts: "{{ TARGET_NODE }}"
  become: true
  roles: 
    - role: 02_server_prerequisites
      tags: always

- name: Check kubeconfig and set environment
  hosts: "{{ TARGET_NODE }}"
  become: true
  tasks:
    - name: Check if kubeconfig exists
      ansible.builtin.stat:
        path: /etc/rancher/rke2/rke2.yaml
      register: kubeconfig_check

    - name: Throw error if kubeconfig doesn't exist
      ansible.builtin.fail:
        msg: "Kubeconfig not found at /etc/rancher/rke2/rke2.yaml"
      when: not kubeconfig_check.stat.exists

    - name: Set kubeconfig environment variable
      ansible.builtin.set_fact:
        rancher_kubeconfig: "/etc/rancher/rke2/rke2.yaml"

- name: Run common tasks 
  hosts: "{{ TARGET_NODE }}"
  become: true
  vars:
    rancher_kubeconfig: "/etc/rancher/rke2/rke2.yaml"
  roles:
    - role: 03_common
      tags: [ common ]

# Deploy PostgreSQL Database First
- name: Deploy PostgreSQL Database
  hosts: "{{ TARGET_NODE }}"
  become: true
  vars:
    rancher_kubeconfig: "/etc/rancher/rke2/rke2.yaml"
  roles:
    - role: 100_postgres
      tags: [ postgres, database ]

# Deploy Redis Cache Second
- name: Deploy Redis Cache
  hosts: "{{ TARGET_NODE }}"
  become: true
  vars:
    rancher_kubeconfig: "/etc/rancher/rke2/rke2.yaml"
  roles:
    - role: 110_redis
      tags: [ redis, cache ]

# Deploy Nextcloud Common Components Third
- name: Run common tasks for nextcloud 
  hosts: "{{ TARGET_NODE }}"
  become: true
  vars:
    rancher_kubeconfig: "/etc/rancher/rke2/rke2.yaml"
  roles:
    - role: 04_common_nextcloud
      tags: [ common_nextcloud, always ]

- name: Create Nextcloud storage directory
  hosts: "{{ TARGET_NODE }}"
  become: true
  tasks:
    - name: Create nextcloud storage directory
      ansible.builtin.file:
        path: "{{ nextcloud_folder }}"
        state: directory
        owner: "33"  # www-data user ID
        group: "33"  # www-data group ID
        mode: '0755'

# Deploy Nextcloud Application Last
- name: InitialInstall Recreate Deployment of Nextcloud
  hosts: "{{ TARGET_NODE }}"
  become: true
  vars:
    rancher_kubeconfig: "/etc/rancher/rke2/rke2.yaml"
  roles:
    - role: 20_recreate
      tags: [ recreate ]